#!/usr/bin/env bash
# Install and configure HAProxy 1.6 on a new Ubuntu 16.04 server

apt-get -y update
apt-get -y install 'haproxy=1.6.*'

cat >> /etc/haproxy/haproxy.cfg << EOF
backend web-backend
	balance roundrobin
	mode http
	server 18916-web-01 3.235.41.156 check
	server 18916-web-02 3.238.126.84 check
frontend web-frontend
	bind *:80
	mode http
	default_backend web-backend
EOF

service haproxy restart
